dataset_name: 'abide'
dataset_root_path: './data/ASDDataset'
df_train: 'train.csv'
df_trainval: train_val.csv
df_val: 'val.csv'
df_test: 'test.csv'
folder_train: '.'
folder_val: '.'
folder_test: '.'
df_classid_classname: 'classid_classname.csv'
