dataset_name: 'bach'
dataset_root_path: './data/BACH/ICIAR2018_BACH_Challenge'
df_train: 'train.csv'
df_trainval: train_val.csv
df_val: 'val.csv'
df_test: 'test.csv'
folder_train: 'Photos'
folder_val: 'Photos'
folder_test: 'Photos'
df_classid_classname: 'classid_classname.csv'
