dataset_name: 'idridme'
dataset_root_path: './data/IDRID'
df_train: 'me_train.csv'
df_trainval: 'me_train_val.csv'
df_val: 'me_val.csv'
df_test: 'me_test.csv'
folder_train: 'B. Disease Grading'
folder_val: 'B. Disease Grading'
folder_test: 'B. Disease Grading'
df_classid_classname: 'me_classid_classname.csv'
