dataset_name: 'idriddr'
dataset_root_path: './data/IDRID'
df_train: 'dr_train.csv'
df_trainval: 'dr_train_val.csv'
df_val: 'dr_val.csv'
df_test: 'dr_test.csv'
folder_train: 'B. Disease Grading'
folder_val: 'B. Disease Grading'
folder_test: 'B. Disease Grading'
df_classid_classname: 'dr_classid_classname.csv'
