dataset_name: 'lublung'
dataset_root_path: './data/LubLung'
df_train: 'train.csv'
df_trainval: train_val.csv
df_val: 'val.csv'
df_test: 'test.csv'
folder_train: 'LubLung'
folder_val: 'LubLung'
folder_test: 'LubLung'
df_classid_classname: 'classid_classname.csv'
