dataset_name: 'lung15k'
dataset_root_path: './data/LC25k/lung_colon_image_set/'
df_train: 'lung15k_train.csv'
df_trainval: lung15k_train_val.csv
df_val: 'lung15k_val.csv'
df_test: 'lung15k_test.csv'
folder_train: 'lung_image_sets'
folder_val: 'lung_image_sets'
folder_test: 'lung_image_sets'
df_classid_classname: 'lung15k_classid_classname.csv'
